fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.2.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '2.1.0'
    apache:
      repo: 'puppetlabs/apache'
      ref: '1.8.1'
    apt:
      repo: 'puppetlabs/apt'
      ref: '2.2.2'
  symlinks:
    mirrorbrain: "#{source_dir}"
