HOSTS:
  ubntu-14-04:
    roles:
      - master
      - database
      - dashboard
    platform: ubuntu-14.04-amd64
    image: ubuntu:14.04
    hypervisor: docker

CONFIG:
  masterless: true
  log_level: verbose
  type: foss
